import type { Metadata } from "next";
import Link from "next/link";
import { BackDoodle, UnderlineDoodle } from "@/doodles";
import { getLevels, museumLink } from "@/lib/content";
import { INTENDED_IMAGE_SOURCE } from "@/lib/image-sources";

export const metadata: Metadata = { title: "About & sources · Louvre Before You Go" };

export default function AboutPage() {
  const levels = getLevels();
  return (
    <main className="soft-fade py-6">
      <Link href="/" className="inline-flex min-h-12 items-center gap-2 font-hand text-lg">
        <BackDoodle className="h-6 w-6" /> Back to the journey
      </Link>

      <h1 className="mt-4 font-hand text-[2.4rem] font-bold leading-none">About &amp; sources</h1>
      <UnderlineDoodle className="mt-1 h-3 w-44" />

      <div className="mt-5 flex flex-col gap-3">
        <p>
          Louvre Before You Go tells one small story a day about one Louvre masterpiece, so you recognise it when
          you&apos;re standing in front of it.
        </p>
        <p>
          Every story was written and checked in advance, and every fact comes from the sources listed below. Nothing on
          this site is generated by AI while you play. Your progress is saved only in this browser.
        </p>
        <p>
          Artwork images are photographs of the real works, never redrawn or filtered. The doodles and artist heads are
          temporary placeholders until the hand-drawn ones arrive.
        </p>
      </div>

      <ol className="mt-8 flex flex-col gap-6">
        {levels.map((l) => {
          const intended = INTENDED_IMAGE_SOURCE[l.artwork.id];
          const louvre = museumLink(l);
          return (
            <li key={l.lesson.id} className="wobbly-alt border-2 border-ink bg-mat px-5 py-4">
              <h2 className="font-hand text-2xl font-bold leading-tight">
                {l.index + 1}. {l.artwork.title}
              </h2>
              <p className="text-sm text-muted">
                {l.artwork.artist === "Unknown" ? "Unknown artist" : l.artwork.artist} · {l.artwork.year} · Level:{" "}
                {l.lesson.title}
              </p>

              <h3 className="mt-3 font-hand text-xl font-bold">Image</h3>
              <p className="text-sm">{l.artwork.imageCredit}</p>
              {!l.imageAvailable && (
                <p className="text-sm text-muted">
                  Photo not added yet (placeholder shown).{" "}
                  {intended && intended !== "TBD" ? (
                    <>
                      Intended source:{" "}
                      <a href={intended} className="break-all text-ultramarine underline" target="_blank" rel="noopener noreferrer">
                        {decodeURIComponent(intended)}
                      </a>
                    </>
                  ) : (
                    "Source: TBD."
                  )}
                </p>
              )}
              {louvre && (
                <p className="text-sm">
                  <a href={louvre} className="font-hand text-base text-ultramarine underline" target="_blank" rel="noopener noreferrer">
                    View at the Louvre →
                  </a>
                </p>
              )}

              <h3 className="mt-3 font-hand text-xl font-bold">Sources for this level</h3>
              <ul className="mt-1 flex list-disc flex-col gap-1 pl-5 text-sm">
                {l.lesson.sources.map((s) => (
                  <li key={s}>
                    {/^https?:\/\//.test(s) ? (
                      <a href={s} className="break-all text-ultramarine underline" target="_blank" rel="noopener noreferrer">
                        {s}
                      </a>
                    ) : (
                      s
                    )}
                  </li>
                ))}
              </ul>
            </li>
          );
        })}
      </ol>
    </main>
  );
}
